### ISSUE TITLE
Question - output to relay ON/OFF 

### ISSUE THREAD

**Issue by ZZerog** [tekdemo/MiniPID-Java#4]
What is the best practice for transform output value from getOutput(sensor,target) to percentage and apply to relay (ON/OFF time in the cycle period)? 

Thank you

**Comment by tekdemo** [comment]
Fundamentally, the math of a PID will eventually settle to the value producing a stable result, so you can quite literally just do `outputDutyCycle = setOutputLimits(0,100)` to get the percentage on time. As long as you apply the output appropriately, the PID will settle on an appropriate duty cycle.

In general though, be careful running relays with a PID. Relays will burn out if switched too quickly, and have a minimum switching time (something around 1 second I believe). They're entirely unsuitable for things like PWM control. So depending on your system, you may run into some tricks to manage this, such as just running the PID loop very slowly, or implementing hysteresis control. Hysteresis can be controlled a few ways, via the input (only change on an error of X) or the output (only change when the output changes by Y), or by a time constraint (At most one switch per N ms), Optimal control will depend on your system dynamics and tuning parameters.

I don't work with relays a lot though, so worth looking into for your application. Often these systems have very good and helpful models to show you how to control things.
