### ISSUE TITLE
Resetting the error-sum on min/max-output can cause oscillations

### ISSUE THREAD

**Issue by DanielWeigl** [tekdemo/MiniPID-Java#7]
At line https://github.com/tekdemo/MiniPID-Java/blob/master/src/com/stormbots/MiniPID.java#L304 you reset the error sum, if the output reaches a limit - but if the output reached the limit because of the I-term going (correctly) towards the limit, then this causes oscillations.

It would (imo) be better to just keep the error sum as is (not resetting and not adding new error)

Example: 
green is the I-term and yellow-dotted the output - which should be driven to its upper bound - but the I-term keeps resetting and thus oscilliating.

![image](https://user-images.githubusercontent.com/1370302/95380237-bf4e1d80-08e6-11eb-9ef3-39120c7cbfeb.png)

After the red line i made this code change:
```
        // Figure out what we're doing with the error.
        if (minOutput != maxOutput && !bounded(output, minOutput, maxOutput)) {
            // NOP
            // keep the error sum as is to ensures a smooth transition when the P term
            // decreases enough for the I term to start acting upon the controller
            // From that point the I term will build up as would be expected
        } else if (outputRampRate != 0 && !bounded(output, lastOutput - outputRampRate, lastOutput + outputRampRate)) {
            errorSum = error;
        } else if (maxIOutput != 0) {
            errorSum = constrain(errorSum + error, -maxError, maxError);
            // In addition to output limiting directly, we also want to prevent I term
            // buildup, so restrict the error directly
        } else {
            errorSum += error;
        }
```

**Comment by HorizonHero** [comment]
need delete line the No.311
`        // Figure out what we're doing with the error.
        if (minOutput != maxOutput && !bounded(output, minOutput, maxOutput)) {
            errorSum = error;
            // keep the error sum as is to ensures a smooth transition when the P term
            // decreases enough for the I term to start acting upon the controller
            // From that point the I term will build up as would be expected
        } else if (outputRampRate != 0 && !bounded(output, lastOutput - outputRampRate, lastOutput + outputRampRate)) {
 //           errorSum = error;//need del this line
        } else if (maxIOutput != 0) {
            errorSum = constrain(errorSum + error, -maxError, maxError);
            // In addition to output limiting directly, we also want to prevent I term
            // buildup, so restrict the error directly
        } else {
            errorSum += error;
        } `

**Comment by tekdemo** [comment]
You are correct. Resolving in the next version.
